### ISSUE TITLE
Load emulator state, render only a frame

### ISSUE THREAD

**Issue by mgerstgrasser** [ppeccin/javatari.js#20]
Thanks for this amazing piece of software! Is it possible to load emulator state information (RAM, registers, anything else that might be needed) to exactly replicate a state? If so, would there be an easy way to just render the most recent frame corresponding that state (i.e. not necessarily further executing the game)? I suspect the second part might be tricky given how (to my understanding) the Atari 2600 renders the screen output, but I wonder if there might be something I don't know about.

**Comment by ppeccin** [comment]
Hi!

Thanks!  :-)

The emulator has the savestates feature. So it is possible to load a
complete and exact machine state that was previously saved.
It also has the feature to pause the emulation and execute it
frame-by-frame.
But since the 2600 does not have a video frame buffer (VRAM), there is no
concept of "current" frame based on the machine state.
You'll need to let a frame's time pass after you loaded the state, so the
machine + CRT can render the next frame.

Of course we could have added an image of the LAST frame generated when you
create a savestate, but that would be a bit artificial and really not
needed for the emulator operation.

So the answer would be:
Load a savestate with the emulation paused, and then render only one next
frame.

Paulo
