### ISSUE TITLE
gamepads do not work properly. stuck in one direction and respond very slowly

### ISSUE THREAD

**Issue by alijani1** [ppeccin/javatari.js#24]
there is something wrong with supporting game pads.  the directions respond very slowly with it mostly stuck in up direction.   you need to add an area in setting to show game pads working and selecting which gamepad to use as a PC might have several gamepads connected.  please update gamepad support as it seems the build is not updated for many years to support modern browser gamnepad support.  gamepads get detected properly on https://gamepad-tester.com so i know gamepads works perfectly .

**Comment by ppeccin** [comment]
Thanks for the report Ali.

Gamepad interface works perfectly for me, and on my tests. It correctly
detects the first 2 gamepads connected to the machine... If you have more
than 2, as of now, you won't be able to select the 3rd one. On the current
version only 2 can be detected, you would have to change the order on you
OS or unplug some gamepads.

What is your environment? Are you on Windows? Linux? Which browser?

Also, please be sure you did not mess the button mappings on the Settings
screen. That could explain the wrong directions.

Paulo

**Comment by JackTar99** [comment]
I'm using the keyboard to control the player and I see behavior very similar to that reported by Ali. Javatari acts as if I'm holding the "up" or sometimes "left" key down so that I can't control the player.  Usually I can gain control by pressing "left", "up", "right", "down" keys enough times but even after that, Javatari will relapse into the "key stuck" mode.

I'm running Windows 10 and have seen the behavior on Chrome, Edge, and Firefox.

**Comment by ppeccin** [comment]
You mean with the keyboard?
Wow, if so there is something very wrong.
Is it a normal wired usb, wireless or bluetooth keyboard?
Did you check if key mappings are not messed up?

Any other heavy tasks running on the machine at the same time?

Paulo

**Comment by JackTar99** [comment]
Wow! Thanks for the quick response. See my responses below. It appears 
that the problem is associated with the left-handed mouse setting. When 
I set my primary button to "Left" (the right-handed setting), the 
problem goes away.

Thanks,
Rich

On 9/20/2021 10:44 AM, ppeccin wrote:
> You mean with the keyboard?
*Yes, using the up, down, right, left arrows.*
> Wow, if so there is something very wrong.
> Is it a normal wired usb, wireless or bluetooth keyboard?
*My keyboard is attached by USB.*
> Did you check if key mappings are not messed up?

*I don't have any special keyboard mappings but I do have my mouse set 
up for left-handed operation and that appears to be the problem. When I 
change the mouse primary button to "left", the problem goes away.*

>
> Any other heavy tasks running on the machine at the same time?
*I always have several browsers, Word  and VSCode open but it happens 
with just the browser open.*

**Comment by JackTar99** [comment]
/Well, shoot. It worked for a while after the change but then relapsed. 
Arghhh.

Wow! Thanks for the quick response. See my responses below. It appears 
that the problem is associated with the left-handed mouse setting. When 
I set my primary button to "Left" (the right-handed setting), the 
problem goes away.//
////
//Thanks,//
//Rich//
////
///
On 9/20/2021 10:44 AM, ppeccin wrote:
> You mean with the keyboard?
*Yes, using the up, down, right, left arrows.*
> Wow, if so there is something very wrong.
> Is it a normal wired usb, wireless or bluetooth keyboard?
*My keyboard is attached by USB.*
> Did you check if key mappings are not messed up?

*I don't have any special keyboard mappings but I do have my mouse set 
up for left-handed operation and that appears to be the problem. When I 
change the mouse primary button to "left", the problem goes away.*

>
> Any other heavy tasks running on the machine at the same time?
*I always have several browsers, Word  and VSCode open but it happens 
with just the browser open.*

**Comment by JackTar99** [comment]
I've been able to try this on several machines and it only fails on one of them:
_Desktop 1 - Dell Inspiron 3670 Windows 10 Pro - Fails_
Desktop 2 - Del Inspiron 3646 Windows 10 Pro (remote access) OK
Laptop 1 - Toshiba Satellite C55-A Windows 10 Home - OK
Laptop 2 - Dell Inspiron 5570 Windows 10 Pro - OK
Hyper-V Centos 8 Instance (remote access)- OK

**Comment by JackTar99** [comment]
I no longer have an issue. I didn't realize that the old joystick tucked away under my desk was connected to anything. When I disconnected it, all the strange behavior went away. Sorry to waste your time!

**Comment by ppeccin** [comment]
Wow....
Glad to hear that!

Paulo
