### ISSUE TITLE
Javatari Support of DPC+

### ISSUE THREAD

**Issue by Lewis2907** [ppeccin/javatari.js#3]
I was checking to see if you or your team was looking at adding DPC game support. I have created a few using Batari Basic and they work fine in Stella, but I am unable to get it to work in Javatari. Thanks in advance for any assistance you can provide.

**Comment by ppeccin** [comment]
Hi!

Javatari already supports DPC (as in Pitfall 2).
But it only recognizes and enables DPC automatically for some known ROMs, like Pitfall 2.
To use it with a custom made game, you will need to specify and force the Cartridge Format when loading the ROM.

Also, there is a so-called DPC+ format, which is very different from normal DPC.
It is a special hardware cartridge that can run software on a built-in ARM processor. Games written for it can only be played in a real Atari if you have that special cartridge plugged in, because its like having a more advanced machine (not an Atari anymore), with a much more powerful processor... Javatari does not emulate this advanced processor yet, and probably won't in the near future.

Please check whether your Batari ROM requires DPC or DPC+. 
Unfortunately the latter will not be possible to run in the current version of Javatari.
