### ISSUE TITLE
how to auto load file on start

### ISSUE THREAD

**Issue by dnelband** [ppeccin/javatari.js#4]
is it possible to specify a file and then load it on i.e without loading cartrdige in the emulator?

**Comment by ppeccin** [comment]
I suppose you are embedding Javatari in you own website, right?
If so, yes, but in the current version you need to specify the URL of the ROM file in Javascript, and the file must be located on the same domain of your main page (because of the Same Origin policy). 

Just set the variable "Javatari.ROM_AUTO_LOAD_URL" to the path of the file you want to load.
Ex:
// Do do this AFTER you load the main javatari.js script file
Javatari.ROM_AUTO_LOAD_URL = "files/Enduro.bin";

If you want to use the main Javatari homepage and load a ROM automatically, currently it is not possible.
On the next release there will be additional ways of loading files, like via Query Parameters, for instance. Then you will be able to link directly to the Javatari homepage and load ROMs automatically, even without having your own webpage.

Paulo

**Comment by dnelband** [comment]
thanks for the quick repsonse!
now i'm having this error:
XMLHttpRequest cannot load XMLHttpRequest cannot load https://bit.no.com:43110/1ChbC1sJDxC8xmyshZjvYaJyVQv994ZaGL/uploads/games/Pac_Man__1982___Atari__Tod_Frye___Sears___CX2646___49_75185_.bin. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'null' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

here is the site: https://bit.no.com:43110/1ChbC1sJDxC8xmyshZjvYaJyVQv994ZaGL.

how can i fix this?

**Comment by ppeccin** [comment]
It may be some configuration issue in you webserver. (it says origin "null"???)
If the emulator and the ROMs are on the same server (same domain), you should not get this error.

I could not access the site you linked. I got all sorts of errors, no emulator was shown, so I could not replicate the problem.

**Comment by ppeccin** [comment]
Closing
