### ISSUE TITLE
Very nice but some questions:

### ISSUE THREAD

**Issue by Zibri** [ppeccin/javatari.js#6]
1) in games like phoenix you need 2 buttons one to fire and one for the barrier.. on screen (on phone) I can only see a red (normal) and Blue (autofire) button...

2) how can I load multiple files so they are saved in localstorage? (or how can I populate localstorage on the first run so to have the roms offline too?)

3) if I upload a zip file with more than one .bin ROM, only the firstis added.. would be nice to have them all added.

**Comment by ppeccin** [comment]
Hey Zibri, answering your questions:

1) The Atari 2600 has only ONE hardware button, there is not a second button. In the game Phoenix, you activate the barrier shield by pulling "down" on the joystick

2) There is no such thing in Javatari. The game list you see when you open the emulator is just a "Recents" list of the last 10 games played. There is no "Library" concept. Storage on web applications is very limited, we cannot have a complete and huge library pre-loaded. So, as a convenience, we store the last 10 games played, and also any savestates you have saved.

3) Yes, it will auto-search and play the first ROM found in the ZIP file. Since we do not have a Library, there is no "add" operation.

As a convenience, you could use some savestates do "save" some games pre-loaded... But if those games happen to be the last 10 games loaded, there is no need to do this since we automatically keep the 10 last games loaded.

What is your use case scenario? Are you using it on the PC, or on mobile devices? Which device?

If you are using it on the iPhone or some device without a file system, the solution is to use some kind of storage to keep all your ROMs, like iCloud, DropBox, Google Docs, etc...
Google Docs even has a "keep offline" feature, so you can load your ROMs while offline.

**Comment by Zibri** [comment]
About phoenix you were right.. my bad...

About the pack, I solved by loading 10 rooms then exporting localStorage. In a sample page I preload localStorage so I have 10 rooms at startup. 

By the way, as you know, atari 2600 rooms are very small for today standards and I bet that they could all fit in localStorage... but I just needed my favourite 10 I owned at the time.

Anyway just for argument sake, a paged "recent" list with pages of 10 ROMs and an "add to library", import library and export library would do. 

Cheers!

Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: ppeccin <notifications@github.com> 
Data:04/09/2017  17:58  (GMT+02:00) 
A: "ppeccin/javatari.js" <javatari.js@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [ppeccin/javatari.js] Very nice but some questions: (#6) 

Hey Zibri, answering your questions:

The Atari 2600 has only ONE hardware button, there is not a second button. In the game Phoenix, you activate the barrier shield by pulling "down" on the joystick

There is no such thing in Javatari. The game list you see when you open the emulator is just a "Recents" list of the last 10 games played. There is no "Library" concept. Storage on web applications is very limited, we cannot have a complete and huge library pre-loaded. So, as a convenience, we store the last 10 games played, and also any savestates you have saved.

Yes, it will auto-search and play the first ROM found in the ZIP file. Since we do not have a Library, there is no "add" operation.

As a convenience, you could use some savestates do "save" some games pre-loaded... But if those games happen to be the last 10 games loaded, there is no need to do this since we automatically keep the 10 last games loaded.

What is your use case scenario? Are you using it on the PC, or on mobile devices? Which device?

If you are using it on the iPhone or some device without a file system, the solution is to use some kind of storage to keep all your ROMs, like iCloud, DropBox, Google Docs, etc...
Google Docs even has a "keep offline" feature, so you can load your ROMs while offline.

**Comment by ppeccin** [comment]
All right!
But just for the sake of information, what do you mean by "sample page"?

**Comment by Zibri** [comment]
I mean I modified index.html and saved it on a local server. Then I loaded with my phone and I had already 10 roms available. Same on any pc. I just with to have about 20. Preloaded in index.html

-------- Messaggio originale --------
Da: ppeccin <notifications@github.com> 
Data:05/09/2017  16:54  (GMT+02:00) 
A: "ppeccin/javatari.js" <javatari.js@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [ppeccin/javatari.js] Very nice but some questions: (#6) 

All right!
But just for the sake of information, what do you mean by "sample page"?

**Comment by ppeccin** [comment]
I see...
But just for you to know, if you want to build a custom page and offer some games, if you take a look at the docs, you'll see that its very easy to build a page and put links or icons where the user can click or drag and launch any amount of games. Many websites with huge libraries use Javatari and do that way.

The "Recent" games feature is more intended for the end user, as a convenience, and not for a library or games website.

Regards

**Comment by Zibri** [comment]
Yes. I know that. Also by URL parameter...

But I wanted a static hotels page with embedded a few (10-20) games. That's it. Unfortunately the recent list is only 10 roms. And I am too lousy with html to modify it to hold 2 pages. :(

-------- Messaggio originale --------
Da: ppeccin <notifications@github.com> 
Data:05/09/2017  18:53  (GMT+02:00) 
A: "ppeccin/javatari.js" <javatari.js@noreply.github.com> 
Cc: Zibri <zibri@zibri.org>,Author <author@noreply.github.com> 
Oggetto: Re: [ppeccin/javatari.js] Very nice but some questions: (#6) 

I see...
But just for you to know, if you want to build a custom page and offer some games, if you take a look at the docs, you'll see that its very easy to build a page and put links or icons where the user can click or drag and launch any amount of games. Many websites with huge libraries use Javatari and do that way.

The "Recent" games feature is more intended for the end user, as a convenience, and not for a library or games website.

Regards
